plugins:
  - name: vyper
  - name: foundry
ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
foundry:
  host: auto
  fork: 
    ethereum:
      mainnet:
        upstream_provider: https://falling-warmhearted-tent.discover.quiknode.pro/f687259088ca474b85f818b935822af9b8ad8afa/