plugins:
  - name: alchemy
  - name: vyper
  - name: foundry
  - name: etherscan
ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
foundry:
  host: auto
  fork: 
    ethereum:
      mainnet:
        upstream_provider: https://eth-mainnet.g.alchemy.com/v2/tW-0aCzXQ9VTqcdp6GbOQqJKmttoIG2k